title: Demoscene.no
description: >- # this means to ignore newlines until "baseurl:"
  Demoscene.no is a website for the Norwegian demoscene community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://demoscene.no"
github_username:  demoscene-no

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10

collections:
  articles:
    output: true

defaults:
  - scope:
      path: "logos"
    values:
      logo: true

links:
  - title: pouet
    url: https://www.pouet.net/
  - title: scene.org
    url: https://www.scene.org/
  - title: quotes
    url: https://quotes.demoscene.no/
  - title: slengpung
    url: http://www.slengpung.com
